ARG IMAGE_NAME="postgres:18.6-alpine3.24"
FROM ${IMAGE_NAME}
ARG IMAGE_NAME

# filename: Dockerfile.04-postgresql
# Alpine 3.24 + PostgreSQL 18.6
# docker pull postgres:18.6-alpine3.24

# EXPOSE 5432

# Variables de entorno del contenedor
ENV THIS_IMAGE="${IMAGE_NAME}"
ENV THIS_IMAGE_TAG="04"
ENV TZ=America/Argentina/Buenos_Aires

# Include & Entrypoint
COPY --chmod=0755 entrypoint.04-postgres-alpine.sh /usr/local/bin/entrypoint.sh

# RUN apk add --no-cache bash nano && \
#     printf '\n### Peter added:\n' >> /root/.bashrc && \
#     printf '%s\n' \
#         "PS1='{\033[01;33m\]$THIS_IMAGE_TAG $THIS_IMAGE\[\033[00m\]} [\[\033[1;31m\]\u@\h\[\033[00m\]:[\033[01;34m\]\w\[\033[00m\]] \$ '" \
#         >> /root/.bashrc && \
#     printf '%s\n' \
#         "alias ls='ls --color=auto'" \
#         "alias ll='ls -alF'" \
#         "alias lk='ls -l'" \
#         >> /root/.bashrc && \
#     date +"0 - %Y-%m-%d  %A  %T - Dockerfile : Image Build [ $THIS_IMAGE_TAG $IMAGE_NAME ]" \
#         > /tmp/00-PostgreSQL-docker-init.log

# WORKDIR /

ENTRYPOINT ["entrypoint.sh"]

# CMD ["/bin/bash"]
CMD ["postgres"]


# ---------------------------------------------------------------------
# BUILD
# image :       04-image-postgresql
# container :   04-postgresql

# build:
# docker build --tag 04-image-postgresql -f Dockerfile.04-postgresql .
# docker history -H 04-image-postgresql --no-trunc

# run:
# docker run --name  04-postgresql  04-image-postgresql
# docker exec -ti 04-postgresql  bash

# remove container & image:
# docker rm -f 04-postgresql && docker rmi 04-image-postgresql
# ---------------------------------------------------------------------
